version: "3"
services:

 # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: mobile_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - /etc/letsencrypt:/etc/ca-certificates
      - ./docker/nginx-prod.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx/
    ports:
      - 80:80
      - 443:443
